### ISSUE TITLE
Fix Power Supply: Power supply does not turn on when plugged in and turned on.

### ISSUE THREAD

**Issue by wildclash** [wilsonjwcsu/Hypoxia-Chamber#8]

**Comment by thekug** [comment]
Verify wiring is setup properly--this was not an issue for us but its possible that a wire become detached. Be careful--there is live 120VAC power in that box. 
We had to replace the 5VDC power adapter for the raspberry pi at one point--not sure why it broke. I believe we left it as an apple charging block.

**Comment by wildclash** [comment]
Wiring for power fixed.
May need to replace some wire clamps to ensure wires are firmly secured.
Began checking along various points incrementally with voltage multimeter, and will add any further issues if necessary, but at this point seems solved.
